version: '3.8'

services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend API (Node.js)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
    depends_on:
      - db
    networks:
      - app-network

  # Frontend (HTML/JS simple)
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge